Project WideWorldImporters {
}
Table Application_Cities {
  CityID int [pk]
  CityName nvarchar
  StateProvinceID int
  Location geography [null]
  LatestRecordedPopulation bigint [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_Cities_Archive {
  CityID int
  CityName nvarchar
  StateProvinceID int
  Location geography [null]
  LatestRecordedPopulation bigint [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_Countries {
  CountryID int [pk]
  CountryName nvarchar
  FormalName nvarchar
  IsoAlpha3Code nvarchar [null]
  IsoNumericCode int [null]
  CountryType nvarchar [null]
  LatestRecordedPopulation bigint [null]
  Continent nvarchar
  Region nvarchar
  Subregion nvarchar
  Border geography [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_Countries_Archive {
  CountryID int
  CountryName nvarchar
  FormalName nvarchar
  IsoAlpha3Code nvarchar [null]
  IsoNumericCode int [null]
  CountryType nvarchar [null]
  LatestRecordedPopulation bigint [null]
  Continent nvarchar
  Region nvarchar
  Subregion nvarchar
  Border geography [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_DeliveryMethods {
  DeliveryMethodID int [pk]
  DeliveryMethodName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_DeliveryMethods_Archive {
  DeliveryMethodID int
  DeliveryMethodName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_HackathonMetadata {
  MetadataID int [pk] [increment]
  ParticipantID int
  ParticipantName nvarchar
  DatabaseName nvarchar
  CreatedDate datetime2
}
Table Application_PaymentMethods {
  PaymentMethodID int [pk]
  PaymentMethodName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_PaymentMethods_Archive {
  PaymentMethodID int
  PaymentMethodName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_People {
  PersonID int [pk]
  FullName nvarchar
  PreferredName nvarchar
  SearchName nvarchar
  IsPermittedToLogon bit
  LogonName nvarchar [null]
  IsExternalLogonProvider bit
  HashedPassword varbinary [null]
  IsSystemUser bit
  IsEmployee bit
  IsSalesperson bit
  UserPreferences nvarchar [null]
  PhoneNumber nvarchar [null]
  FaxNumber nvarchar [null]
  EmailAddress nvarchar [null]
  Photo varbinary [null]
  CustomFields nvarchar [null]
  OtherLanguages nvarchar [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_People_Archive {
  PersonID int
  FullName nvarchar
  PreferredName nvarchar
  SearchName nvarchar
  IsPermittedToLogon bit
  LogonName nvarchar [null]
  IsExternalLogonProvider bit
  HashedPassword varbinary [null]
  IsSystemUser bit
  IsEmployee bit
  IsSalesperson bit
  UserPreferences nvarchar [null]
  PhoneNumber nvarchar [null]
  FaxNumber nvarchar [null]
  EmailAddress nvarchar [null]
  Photo varbinary [null]
  CustomFields nvarchar [null]
  OtherLanguages nvarchar [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_StateProvinces {
  StateProvinceID int [pk]
  StateProvinceCode nvarchar
  StateProvinceName nvarchar
  CountryID int
  SalesTerritory nvarchar
  Border geography [null]
  LatestRecordedPopulation bigint [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_StateProvinces_Archive {
  StateProvinceID int
  StateProvinceCode nvarchar
  StateProvinceName nvarchar
  CountryID int
  SalesTerritory nvarchar
  Border geography [null]
  LatestRecordedPopulation bigint [null]
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_SystemParameters {
  SystemParameterID int [pk]
  DeliveryAddressLine1 nvarchar
  DeliveryAddressLine2 nvarchar [null]
  DeliveryCityID int
  DeliveryPostalCode nvarchar
  DeliveryLocation geography
  PostalAddressLine1 nvarchar
  PostalAddressLine2 nvarchar [null]
  PostalCityID int
  PostalPostalCode nvarchar
  ApplicationSettings nvarchar
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Application_TransactionTypes {
  TransactionTypeID int [pk]
  TransactionTypeName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Application_TransactionTypes_Archive {
  TransactionTypeID int
  TransactionTypeName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Purchasing_PurchaseOrderLines {
  PurchaseOrderLineID int [pk]
  PurchaseOrderID int
  StockItemID int
  OrderedOuters int
  Description nvarchar
  ReceivedOuters int
  PackageTypeID int
  ExpectedUnitPricePerOuter decimal [null]
  LastReceiptDate date [null]
  IsOrderLineFinalized bit
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Purchasing_PurchaseOrders {
  PurchaseOrderID int [pk]
  SupplierID int
  OrderDate date
  DeliveryMethodID int
  ContactPersonID int
  ExpectedDeliveryDate date [null]
  SupplierReference nvarchar [null]
  IsOrderFinalized bit
  Comments nvarchar [null]
  InternalComments nvarchar [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Purchasing_SupplierCategories {
  SupplierCategoryID int [pk]
  SupplierCategoryName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Purchasing_SupplierCategories_Archive {
  SupplierCategoryID int
  SupplierCategoryName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Purchasing_Suppliers {
  SupplierID int [pk]
  SupplierName nvarchar
  SupplierCategoryID int
  PrimaryContactPersonID int
  AlternateContactPersonID int
  DeliveryMethodID int [null]
  DeliveryCityID int
  PostalCityID int
  SupplierReference nvarchar [null]
  BankAccountName nvarchar [null]
  BankAccountBranch nvarchar [null]
  BankAccountCode nvarchar [null]
  BankAccountNumber nvarchar [null]
  BankInternationalCode nvarchar [null]
  PaymentDays int
  InternalComments nvarchar [null]
  PhoneNumber nvarchar
  FaxNumber nvarchar
  WebsiteURL nvarchar
  DeliveryAddressLine1 nvarchar
  DeliveryAddressLine2 nvarchar [null]
  DeliveryPostalCode nvarchar
  DeliveryLocation geography [null]
  PostalAddressLine1 nvarchar
  PostalAddressLine2 nvarchar [null]
  PostalPostalCode nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Purchasing_Suppliers_Archive {
  SupplierID int
  SupplierName nvarchar
  SupplierCategoryID int
  PrimaryContactPersonID int
  AlternateContactPersonID int
  DeliveryMethodID int [null]
  DeliveryCityID int
  PostalCityID int
  SupplierReference nvarchar [null]
  BankAccountName nvarchar [null]
  BankAccountBranch nvarchar [null]
  BankAccountCode nvarchar [null]
  BankAccountNumber nvarchar [null]
  BankInternationalCode nvarchar [null]
  PaymentDays int
  InternalComments nvarchar [null]
  PhoneNumber nvarchar
  FaxNumber nvarchar
  WebsiteURL nvarchar
  DeliveryAddressLine1 nvarchar
  DeliveryAddressLine2 nvarchar [null]
  DeliveryPostalCode nvarchar
  DeliveryLocation geography [null]
  PostalAddressLine1 nvarchar
  PostalAddressLine2 nvarchar [null]
  PostalPostalCode nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Purchasing_SupplierTransactions {
  SupplierTransactionID int [pk]
  SupplierID int
  TransactionTypeID int
  PurchaseOrderID int [null]
  PaymentMethodID int [null]
  SupplierInvoiceNumber nvarchar [null]
  TransactionDate date
  AmountExcludingTax decimal
  TaxAmount decimal
  TransactionAmount decimal
  OutstandingBalance decimal
  FinalizationDate date [null]
  IsFinalized bit [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_BuyingGroups {
  BuyingGroupID int [pk]
  BuyingGroupName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_BuyingGroups_Archive {
  BuyingGroupID int
  BuyingGroupName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_CustomerCategories {
  CustomerCategoryID int [pk]
  CustomerCategoryName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_CustomerCategories_Archive {
  CustomerCategoryID int
  CustomerCategoryName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_Customers {
  CustomerID int [pk]
  CustomerName nvarchar
  BillToCustomerID int
  CustomerCategoryID int
  BuyingGroupID int [null]
  PrimaryContactPersonID int
  AlternateContactPersonID int [null]
  DeliveryMethodID int
  DeliveryCityID int
  PostalCityID int
  CreditLimit decimal [null]
  AccountOpenedDate date
  StandardDiscountPercentage decimal
  IsStatementSent bit
  IsOnCreditHold bit
  PaymentDays int
  PhoneNumber nvarchar
  FaxNumber nvarchar
  DeliveryRun nvarchar [null]
  RunPosition nvarchar [null]
  WebsiteURL nvarchar
  DeliveryAddressLine1 nvarchar
  DeliveryAddressLine2 nvarchar [null]
  DeliveryPostalCode nvarchar
  DeliveryLocation geography [null]
  PostalAddressLine1 nvarchar
  PostalAddressLine2 nvarchar [null]
  PostalPostalCode nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_Customers_Archive {
  CustomerID int
  CustomerName nvarchar
  BillToCustomerID int
  CustomerCategoryID int
  BuyingGroupID int [null]
  PrimaryContactPersonID int
  AlternateContactPersonID int [null]
  DeliveryMethodID int
  DeliveryCityID int
  PostalCityID int
  CreditLimit decimal [null]
  AccountOpenedDate date
  StandardDiscountPercentage decimal
  IsStatementSent bit
  IsOnCreditHold bit
  PaymentDays int
  PhoneNumber nvarchar
  FaxNumber nvarchar
  DeliveryRun nvarchar [null]
  RunPosition nvarchar [null]
  WebsiteURL nvarchar
  DeliveryAddressLine1 nvarchar
  DeliveryAddressLine2 nvarchar [null]
  DeliveryPostalCode nvarchar
  DeliveryLocation geography [null]
  PostalAddressLine1 nvarchar
  PostalAddressLine2 nvarchar [null]
  PostalPostalCode nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Sales_CustomerTransactions {
  CustomerTransactionID int [pk]
  CustomerID int
  TransactionTypeID int
  InvoiceID int [null]
  PaymentMethodID int [null]
  TransactionDate date
  AmountExcludingTax decimal
  TaxAmount decimal
  TransactionAmount decimal
  OutstandingBalance decimal
  FinalizationDate date [null]
  IsFinalized bit [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_InvoiceLines {
  InvoiceLineID int [pk]
  InvoiceID int
  StockItemID int
  Description nvarchar
  PackageTypeID int
  Quantity int
  UnitPrice decimal [null]
  TaxRate decimal
  TaxAmount decimal
  LineProfit decimal
  ExtendedPrice decimal
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_Invoices {
  InvoiceID int [pk]
  CustomerID int
  BillToCustomerID int
  OrderID int [null]
  DeliveryMethodID int
  ContactPersonID int
  AccountsPersonID int
  SalespersonPersonID int
  PackedByPersonID int
  InvoiceDate date
  CustomerPurchaseOrderNumber nvarchar [null]
  IsCreditNote bit
  CreditNoteReason nvarchar [null]
  Comments nvarchar [null]
  DeliveryInstructions nvarchar [null]
  InternalComments nvarchar [null]
  TotalDryItems int
  TotalChillerItems int
  DeliveryRun nvarchar [null]
  RunPosition nvarchar [null]
  ReturnedDeliveryData nvarchar [null]
  ConfirmedDeliveryTime datetime2 [null]
  ConfirmedReceivedBy nvarchar [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_OrderLines {
  OrderLineID int [pk]
  OrderID int
  StockItemID int
  Description nvarchar
  PackageTypeID int
  Quantity int
  UnitPrice decimal [null]
  TaxRate decimal
  PickedQuantity int
  PickingCompletedWhen datetime2 [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_Orders {
  OrderID int [pk]
  CustomerID int
  SalespersonPersonID int
  PickedByPersonID int [null]
  ContactPersonID int
  BackorderOrderID int [null]
  OrderDate date
  ExpectedDeliveryDate date
  CustomerPurchaseOrderNumber nvarchar [null]
  IsUndersupplyBackordered bit
  Comments nvarchar [null]
  DeliveryInstructions nvarchar [null]
  InternalComments nvarchar [null]
  PickingCompletedWhen datetime2 [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Sales_SpecialDeals {
  SpecialDealID int [pk]
  StockItemID int [null]
  CustomerID int [null]
  BuyingGroupID int [null]
  CustomerCategoryID int [null]
  StockGroupID int [null]
  DealDescription nvarchar
  StartDate date
  EndDate date
  DiscountAmount decimal [null]
  DiscountPercentage decimal [null]
  UnitPrice decimal [null]
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Warehouse_ColdRoomTemperatures {
  ColdRoomTemperatureID bigint [pk] [increment]
  ColdRoomSensorNumber int
  RecordedWhen datetime2
  Temperature decimal
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_ColdRoomTemperatures_Archive {
  ColdRoomTemperatureID bigint
  ColdRoomSensorNumber int
  RecordedWhen datetime2
  Temperature decimal
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_Colors {
  ColorID int [pk]
  ColorName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_Colors_Archive {
  ColorID int
  ColorName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_PackageTypes {
  PackageTypeID int [pk]
  PackageTypeName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_PackageTypes_Archive {
  PackageTypeID int
  PackageTypeName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_StockGroups {
  StockGroupID int [pk]
  StockGroupName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_StockGroups_Archive {
  StockGroupID int
  StockGroupName nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_StockItemHoldings {
  StockItemID int [pk]
  QuantityOnHand int
  BinLocation nvarchar
  LastStocktakeQuantity int
  LastCostPrice decimal
  ReorderLevel int
  TargetStockLevel int
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Warehouse_StockItems {
  StockItemID int [pk]
  StockItemName nvarchar
  SupplierID int
  ColorID int [null]
  UnitPackageID int
  OuterPackageID int
  Brand nvarchar [null]
  Size nvarchar [null]
  LeadTimeDays int
  QuantityPerOuter int
  IsChillerStock bit
  Barcode nvarchar [null]
  TaxRate decimal
  UnitPrice decimal
  RecommendedRetailPrice decimal [null]
  TypicalWeightPerUnit decimal
  MarketingComments nvarchar [null]
  InternalComments nvarchar [null]
  Photo varbinary [null]
  CustomFields nvarchar [null]
  Tags nvarchar [null]
  SearchDetails nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_StockItems_Archive {
  StockItemID int
  StockItemName nvarchar
  SupplierID int
  ColorID int [null]
  UnitPackageID int
  OuterPackageID int
  Brand nvarchar [null]
  Size nvarchar [null]
  LeadTimeDays int
  QuantityPerOuter int
  IsChillerStock bit
  Barcode nvarchar [null]
  TaxRate decimal
  UnitPrice decimal
  RecommendedRetailPrice decimal [null]
  TypicalWeightPerUnit decimal
  MarketingComments nvarchar [null]
  InternalComments nvarchar [null]
  Photo varbinary [null]
  CustomFields nvarchar [null]
  Tags nvarchar [null]
  SearchDetails nvarchar
  LastEditedBy int
  ValidFrom datetime2
  ValidTo datetime2
}
Table Warehouse_StockItemStockGroups {
  StockItemStockGroupID int [pk]
  StockItemID int
  StockGroupID int
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Warehouse_StockItemTransactions {
  StockItemTransactionID int [pk]
  StockItemID int
  TransactionTypeID int
  CustomerID int [null]
  InvoiceID int [null]
  SupplierID int [null]
  PurchaseOrderID int [null]
  TransactionOccurredWhen datetime2
  Quantity decimal
  LastEditedBy int
  LastEditedWhen datetime2
}
Table Warehouse_VehicleTemperatures {
  VehicleTemperatureID bigint [pk] [increment]
  VehicleRegistration nvarchar
  ChillerSensorNumber int
  RecordedWhen datetime2
  Temperature decimal
  FullSensorData nvarchar [null]
  IsCompressed bit
  CompressedSensorData varbinary [null]
}
Ref: BuyingGroups.[LastEditedBy] > People.[PersonID]
Ref: Cities.[LastEditedBy] > People.[PersonID]
Ref: Cities.[StateProvinceID] > StateProvinces.[StateProvinceID]
Ref: Colors.[LastEditedBy] > People.[PersonID]
Ref: Countries.[LastEditedBy] > People.[PersonID]
Ref: CustomerCategories.[LastEditedBy] > People.[PersonID]
Ref: Customers.[PrimaryContactPersonID] > People.[PersonID]
Ref: Customers.[AlternateContactPersonID] > People.[PersonID]
Ref: Customers.[LastEditedBy] > People.[PersonID]
Ref: Customers.[BillToCustomerID] > Customers.[CustomerID]
Ref: Customers.[DeliveryCityID] > Cities.[CityID]
Ref: Customers.[PostalCityID] > Cities.[CityID]
Ref: Customers.[DeliveryMethodID] > DeliveryMethods.[DeliveryMethodID]
Ref: Customers.[BuyingGroupID] > BuyingGroups.[BuyingGroupID]
Ref: Customers.[CustomerCategoryID] > CustomerCategories.[CustomerCategoryID]
Ref: CustomerTransactions.[InvoiceID] > Invoices.[InvoiceID]
Ref: CustomerTransactions.[TransactionTypeID] > TransactionTypes.[TransactionTypeID]
Ref: CustomerTransactions.[PaymentMethodID] > PaymentMethods.[PaymentMethodID]
Ref: CustomerTransactions.[CustomerID] > Customers.[CustomerID]
Ref: CustomerTransactions.[LastEditedBy] > People.[PersonID]
Ref: DeliveryMethods.[LastEditedBy] > People.[PersonID]
Ref: InvoiceLines.[LastEditedBy] > People.[PersonID]
Ref: InvoiceLines.[PackageTypeID] > PackageTypes.[PackageTypeID]
Ref: InvoiceLines.[StockItemID] > StockItems.[StockItemID]
Ref: InvoiceLines.[InvoiceID] > Invoices.[InvoiceID]
Ref: Invoices.[DeliveryMethodID] > DeliveryMethods.[DeliveryMethodID]
Ref: Invoices.[CustomerID] > Customers.[CustomerID]
Ref: Invoices.[BillToCustomerID] > Customers.[CustomerID]
Ref: Invoices.[OrderID] > Orders.[OrderID]
Ref: Invoices.[SalespersonPersonID] > People.[PersonID]
Ref: Invoices.[PackedByPersonID] > People.[PersonID]
Ref: Invoices.[LastEditedBy] > People.[PersonID]
Ref: Invoices.[ContactPersonID] > People.[PersonID]
Ref: Invoices.[AccountsPersonID] > People.[PersonID]
Ref: OrderLines.[StockItemID] > StockItems.[StockItemID]
Ref: OrderLines.[LastEditedBy] > People.[PersonID]
Ref: OrderLines.[OrderID] > Orders.[OrderID]
Ref: OrderLines.[PackageTypeID] > PackageTypes.[PackageTypeID]
Ref: Orders.[BackorderOrderID] > Orders.[OrderID]
Ref: Orders.[CustomerID] > Customers.[CustomerID]
Ref: Orders.[SalespersonPersonID] > People.[PersonID]
Ref: Orders.[PickedByPersonID] > People.[PersonID]
Ref: Orders.[ContactPersonID] > People.[PersonID]
Ref: Orders.[LastEditedBy] > People.[PersonID]
Ref: PackageTypes.[LastEditedBy] > People.[PersonID]
Ref: PaymentMethods.[LastEditedBy] > People.[PersonID]
Ref: People.[LastEditedBy] > People.[PersonID]
Ref: PurchaseOrderLines.[LastEditedBy] > People.[PersonID]
Ref: PurchaseOrderLines.[StockItemID] > StockItems.[StockItemID]
Ref: PurchaseOrderLines.[PurchaseOrderID] > PurchaseOrders.[PurchaseOrderID]
Ref: PurchaseOrderLines.[PackageTypeID] > PackageTypes.[PackageTypeID]
Ref: PurchaseOrders.[SupplierID] > Suppliers.[SupplierID]
Ref: PurchaseOrders.[ContactPersonID] > People.[PersonID]
Ref: PurchaseOrders.[LastEditedBy] > People.[PersonID]
Ref: PurchaseOrders.[DeliveryMethodID] > DeliveryMethods.[DeliveryMethodID]
Ref: SpecialDeals.[CustomerCategoryID] > CustomerCategories.[CustomerCategoryID]
Ref: SpecialDeals.[BuyingGroupID] > BuyingGroups.[BuyingGroupID]
Ref: SpecialDeals.[StockGroupID] > StockGroups.[StockGroupID]
Ref: SpecialDeals.[StockItemID] > StockItems.[StockItemID]
Ref: SpecialDeals.[LastEditedBy] > People.[PersonID]
Ref: SpecialDeals.[CustomerID] > Customers.[CustomerID]
Ref: StateProvinces.[CountryID] > Countries.[CountryID]
Ref: StateProvinces.[LastEditedBy] > People.[PersonID]
Ref: StockGroups.[LastEditedBy] > People.[PersonID]
Ref: StockItemHoldings.[LastEditedBy] > People.[PersonID]
Ref: StockItemHoldings.[StockItemID] > StockItems.[StockItemID]
Ref: StockItems.[LastEditedBy] > People.[PersonID]
Ref: StockItems.[SupplierID] > Suppliers.[SupplierID]
Ref: StockItems.[ColorID] > Colors.[ColorID]
Ref: StockItems.[UnitPackageID] > PackageTypes.[PackageTypeID]
Ref: StockItems.[OuterPackageID] > PackageTypes.[PackageTypeID]
Ref: StockItemStockGroups.[StockGroupID] > StockGroups.[StockGroupID]
Ref: StockItemStockGroups.[LastEditedBy] > People.[PersonID]
Ref: StockItemStockGroups.[StockItemID] > StockItems.[StockItemID]
Ref: StockItemTransactions.[LastEditedBy] > People.[PersonID]
Ref: StockItemTransactions.[PurchaseOrderID] > PurchaseOrders.[PurchaseOrderID]
Ref: StockItemTransactions.[CustomerID] > Customers.[CustomerID]
Ref: StockItemTransactions.[SupplierID] > Suppliers.[SupplierID]
Ref: StockItemTransactions.[StockItemID] > StockItems.[StockItemID]
Ref: StockItemTransactions.[TransactionTypeID] > TransactionTypes.[TransactionTypeID]
Ref: StockItemTransactions.[InvoiceID] > Invoices.[InvoiceID]
Ref: SupplierCategories.[LastEditedBy] > People.[PersonID]
Ref: Suppliers.[DeliveryMethodID] > DeliveryMethods.[DeliveryMethodID]
Ref: Suppliers.[PrimaryContactPersonID] > People.[PersonID]
Ref: Suppliers.[AlternateContactPersonID] > People.[PersonID]
Ref: Suppliers.[LastEditedBy] > People.[PersonID]
Ref: Suppliers.[DeliveryCityID] > Cities.[CityID]
Ref: Suppliers.[PostalCityID] > Cities.[CityID]
Ref: Suppliers.[SupplierCategoryID] > SupplierCategories.[SupplierCategoryID]
Ref: SupplierTransactions.[TransactionTypeID] > TransactionTypes.[TransactionTypeID]
Ref: SupplierTransactions.[PaymentMethodID] > PaymentMethods.[PaymentMethodID]
Ref: SupplierTransactions.[SupplierID] > Suppliers.[SupplierID]
Ref: SupplierTransactions.[PurchaseOrderID] > PurchaseOrders.[PurchaseOrderID]
Ref: SupplierTransactions.[LastEditedBy] > People.[PersonID]
Ref: SystemParameters.[LastEditedBy] > People.[PersonID]
Ref: SystemParameters.[DeliveryCityID] > Cities.[CityID]
Ref: SystemParameters.[PostalCityID] > Cities.[CityID]
Ref: TransactionTypes.[LastEditedBy] > People.[PersonID]